# 01_Data_Cleaning

In [1]:
import pandas as pd

csv_path = "../data/raw/spotify_tracks.csv"
df = pd.read_csv(csv_path)

# 'track_id' column cast to string and strip of whitespace
df['track_id'] = df['track_id'].astype(str).str.strip()

# Keep only records where the length of 'track_id' is exactly 22 chars
df = df[df['track_id'].str.len() == 22]

print(f"Sanitized dataset rows: {len(df)}")

# Task 1: dropping index column -> carries no information
df = df.drop(columns='Unnamed: 0')
df.head(5)

Sanitized dataset rows: 114000

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

## Task 1&2: Handle Null Values

In [2]:
df['artists'] = df['artists'].fillna('Unknown')
df['album_name'] = df['album_name'].fillna('Unknown')
df['track_name'] = df['track_name'].fillna('Unknown')

# Any row that contains missing value
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [track_id, artists, album_name, track_name, popularity, duration_ms, explicit, danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo, time_signature, track_genre]
Index: []

## Task 4: New Columns

In [3]:
df['duration_min'] = df['duration_ms'] / 60000

df['is_live'] = df['liveness'] > 0.8

df['is_instrumental'] = df['instrumentalness'] > 0.5

df['is_spoken_word'] = df['speechiness'] > 0.66

musical_modes = {
    0: "Minor",
    1: "Major"
}

musical_keys = {
    0: "C",
    1: "C#",
    2: "D",
    3: "D#",
    4: "E",
    5: "F",
    6: "F#",
    7: "G",
    8: "G#",
    9: "A",
    10: "A#",
    11: "B"
}

df['key_name'] = df['key'].map(musical_keys)

df['mode_name'] = df['mode'].map(musical_modes)

df.head(5)

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,valence,tempo,time_signature,track_genre,duration_min,is_live,is_instrumental,is_spoken_word,key_name,mode_name
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,...,0.715,87.917,4,acoustic,3.844433,False,False,False,C#,Minor
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,...,0.267,77.489,4,acoustic,2.493500,False,False,False,C#,Major
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,...,0.120,76.332,4,acoustic,3.513767,False,False,False,C,Major
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,...,0.143,181.740,3,acoustic,3.365550,False,False,False,C,Major
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,...,0.167,119.949,4,acoustic,3.314217,False,False,False,D,Major

## Normalize the 'Artists' column

In [4]:
# Extract the 'track_id' and 'artists' columns, and drop null values
artists_raw = df[['track_id', 'artists']].dropna()

# Split the string 'artists' column by the semicolon separator (';')
artists_raw['artists'] = df['artists'].str.split(';')

#Explode the list-valued 'artists' column into distinct rows
artists_exploded = df.explode('artists')

# Strip any leading/trailing spaces from the exploded 'artists' column
artists_exploded['artists'] = artists_exploded['artists'].str.strip()

# Create a unique lookup table of artist names (with no duplicates)
artists_lookup = pd.DataFrame({'artist_name': artists_exploded['artists'].unique()}).dropna()

## Task 3: Popularity-Based Deduplication

In [5]:
# Track duplicate counts
print(df['track_id'].value_counts().head(10))

# Create full dataset before deduplication
tracks_full = df.copy()

# Sort by popularity in descending order
df_sorted = df.sort_values('popularity', ascending=False)

# Drop duplicate rows based on 'track_id'
tracks_deduped = df_sorted.drop_duplicates(subset='track_id', keep='first')

# Extract distinct albums and genres for lookup
albums_lookup = df[['album_name']].dropna().drop_duplicates()
genres_lookup = df[['track_genre']].dropna().drop_duplicates()

tracks_deduped.head()

track_id
6S3JlDAGk3uu3NtZbPnuhS    9
2kkvB3RNRzwjFdGhaUA0tz    8
2Ey6v4Sekh3Z0RUSISRosD    8
2vU6bm5hVF2idVknGzqyPL    7
4GPQDyw9hC1DiZVh0ouDVL    7
5ftfVzSLIi5ZxYdNbRtf41    7
6bzWr3EpSEolVwlbLk58il    7
2aaClnypAakdAmLw74JXxB    7
4WJTKbNJQ41zXnb84jSWaj    7
0e5LcankE0UyJUuCoq1uH2    7
Name: count, dtype: int64

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,valence,tempo,time_signature,track_genre,duration_min,is_live,is_instrumental,is_spoken_word,key_name,mode_name
20001,3nqQXoyQOWXiESFLlDF1hG,Sam Smith;Kim Petras,Unholy (feat. Kim Petras),Unholy (feat. Kim Petras),100,156943,False,0.714,0.472,2,...,0.238,131.121,4,dance,2.615717,False,False,False,D,Major
51664,2tTmW7RDtMQtBk7m2rYeSw,Bizarrap;Quevedo,"Quevedo: Bzrp Music Sessions, Vol. 52","Quevedo: Bzrp Music Sessions, Vol. 52",99,198937,False,0.621,0.782,2,...,0.550,128.033,4,hip-hop,3.315617,False,False,False,D,Major
81210,4uUG5RXrOk84mYEfFvj3cK,David Guetta;Bebe Rexha,I'm Good (Blue),I'm Good (Blue),98,175238,True,0.561,0.965,7,...,0.304,128.040,4,pop,2.920633,False,False,False,G,Minor
89411,5ww2BF9slyYgNOk37BlC4u,Manuel Turizo,La Bachata,La Bachata,98,162637,False,0.835,0.679,7,...,0.850,124.980,4,reggaeton,2.710617,False,False,False,G,Minor
68305,6Sq7ltF9Qa7SNFBsV5Cogx,Bad Bunny;Chencho Corleone,Un Verano Sin Ti,Me Porto Bonito,97,178567,True,0.911,0.712,1,...,0.425,92.005,4,latino,2.976117,False,False,False,C#,Minor

## Task 5: Validate Ranges

In [6]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)
df.describe().T[['min', 'max']]

                     min         max
popularity         0.000     100.000
duration_ms        0.000 5237295.000
danceability       0.000       0.985
energy             0.000       1.000
key                0.000      11.000
loudness         -49.531       4.532
mode               0.000       1.000
speechiness        0.000       0.965
acousticness       0.000       0.996
instrumentalness   0.000       1.000
liveness           0.000       1.000
valence            0.000       0.995
tempo              0.000     243.372
time_signature     0.000       5.000
duration_min       0.000      87.288

In [7]:
# The 0.0 Tempo & 0.0 Duration Tracks
df[df['tempo'] == 0][['artists', 'track_name', 'track_genre', 'duration_min']]

,artists,track_name,track_genre,duration_min
4131,Max Richter;Lang Lang,The Departure,ambient,2.525
4379,Dario Marianelli;Jack Liebeck;Benjamin Wallfisch,The End of Childhood (feat. Jack Liebeck),ambient,1.221
4664,Sylvain Chauveau,Ferme Les Yeux,ambient,1.142
45670,Little Symphony,Campomoro,guitar,2.479
45720,Little Symphony,Ritornello,guitar,1.700
...,...,...,...,...
101988,Granular,Tin White Noise,sleep,3.034
101993,Rain Sounds,Rain: Natural Recording,sleep,1.404
113428,El Ruido Blanco;Soñoliento Juan;Mantra para Do...,Aire de verano,world-music,2.133
113688,El Ruido Blanco,Ruido Rosa Puro - Una Hora Versión,world-music,60.028
113856,Колыбельная-земля,Пылесос (Белый шум),world-music,5.036

In [8]:
#The 87-Minute Track (duration_min Max)
df[df['duration_min'] > 60][['artists', 'track_name', 'track_genre', 'duration_min']]

,artists,track_name,track_genre,duration_min
10935,Timo Maas,Crossing Wires 002 - Continuous DJ Mix,breakbeat,79.817
10984,Timo Maas,Crossing Wires 002 - Continuous DJ Mix,breakbeat,79.817
13195,Mark Farina,Greenhouse Construction,chicago-house,72.245
13245,Mark Farina,Live In Tokyo - Continuous Mix,chicago-house,72.330
13344,Mark Farina,House of Om - Mark Farina - Continuous Mix,chicago-house,74.125
24348,Seth Troxler,The Lab 03 - Continuous DJ Mix Part 1,detroit-techno,78.838
24747,Kevin Saunderson,Kevin Saunderson History Elevate - Continuous Mix,detroit-techno,61.279
27926,Lenzman;Dan Stezo,"NQ State of Mind, Vol. 1 - Continuous DJ Mix",drum-and-bass,70.770
45063,Estas Tonne,Internal Flight (Remastered),guitar,64.605
45900,Estas Tonne,Internal Flight,guitar,64.605
73617,Tale Of Us,Unity (Voyage Mix) Pt. 1,minimal-techno,87.288
73840,Loco Dice,Amnesia Ibiza Underground 10 DJ Mix,minimal-techno,76.065
101390,Ocean Sounds,Ocean Waves Sounds,sleep,68.671
101517,Electric Dreams,Electric Fan (Sound Masking Fan),sleep,60.000
101940,Vacuum Cleaner White Noise,Vacuum Cleaner White Noise,sleep,60.002
113688,El Ruido Blanco,Ruido Rosa Puro - Una Hora Versión,world-music,60.028

## Task 6: Clean data to PostgreSQL

In [9]:
#Saving as CSV format to data/cleaned
tracks_deduped.to_csv('../data/cleaned/tracks_deduped.csv', index=False, encoding='utf-8')
tracks_full.to_csv('../data/cleaned/tracks_full.csv', index=False, encoding='utf-8')

In [14]:
#Database Ingestion
from sqlalchemy import create_engine
engine = create_engine('postgresql://akmalyerzakov:$password$@localhost:5432/spotify')

tracks_deduped.to_sql('tracks_deduped', con=engine, if_exists='replace', index=False)
tracks_full.to_sql('tracks_full', con=engine, if_exists='replace', index=False)

print("Tables successfully created in PostgreSQL local_database/spotify!")

Tables successfully created in PostgreSQL local_database/spotify!